// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_response_header.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "rpc_response_header.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class RpcResponseHeaderDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<RpcResponseHeader> {
} _RpcResponseHeader_default_instance_;

namespace protobuf_rpc_5fresponse_5fheader_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcResponseHeader, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcResponseHeader, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcResponseHeader, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(RpcResponseHeader, args_size_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(RpcResponseHeader)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_RpcResponseHeader_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "rpc_response_header.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _RpcResponseHeader_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _RpcResponseHeader_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\031rpc_response_header.proto\"S\n\021RpcRespon"
      "seHeader\022\032\n\006status\030\001 \001(\0162\n.ErrorCode\022\017\n\007"
      "message\030\002 \001(\t\022\021\n\targs_size\030\003 \001(\005*h\n\tErro"
      "rCode\022\013\n\007SUCCESS\020\000\022\021\n\rUNKNOWN_ERROR\020\001\022\023\n"
      "\017INVALID_REQUEST\020\002\022\017\n\013AUTH_FAILED\020\003\022\025\n\021P"
      "ERMISSION_DENIED\020\004b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 226);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "rpc_response_header.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_rpc_5fresponse_5fheader_2eproto

const ::google::protobuf::EnumDescriptor* ErrorCode_descriptor() {
  protobuf_rpc_5fresponse_5fheader_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_rpc_5fresponse_5fheader_2eproto::file_level_enum_descriptors[0];
}
bool ErrorCode_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RpcResponseHeader::kStatusFieldNumber;
const int RpcResponseHeader::kMessageFieldNumber;
const int RpcResponseHeader::kArgsSizeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RpcResponseHeader::RpcResponseHeader()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_rpc_5fresponse_5fheader_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:RpcResponseHeader)
}
RpcResponseHeader::RpcResponseHeader(const RpcResponseHeader& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  ::memcpy(&status_, &from.status_,
    reinterpret_cast<char*>(&args_size_) -
    reinterpret_cast<char*>(&status_) + sizeof(args_size_));
  // @@protoc_insertion_point(copy_constructor:RpcResponseHeader)
}

void RpcResponseHeader::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&status_, 0, reinterpret_cast<char*>(&args_size_) -
    reinterpret_cast<char*>(&status_) + sizeof(args_size_));
  _cached_size_ = 0;
}

RpcResponseHeader::~RpcResponseHeader() {
  // @@protoc_insertion_point(destructor:RpcResponseHeader)
  SharedDtor();
}

void RpcResponseHeader::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RpcResponseHeader::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* RpcResponseHeader::descriptor() {
  protobuf_rpc_5fresponse_5fheader_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_rpc_5fresponse_5fheader_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RpcResponseHeader& RpcResponseHeader::default_instance() {
  protobuf_rpc_5fresponse_5fheader_2eproto::InitDefaults();
  return *internal_default_instance();
}

RpcResponseHeader* RpcResponseHeader::New(::google::protobuf::Arena* arena) const {
  RpcResponseHeader* n = new RpcResponseHeader;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void RpcResponseHeader::Clear() {
// @@protoc_insertion_point(message_clear_start:RpcResponseHeader)
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&status_, 0, reinterpret_cast<char*>(&args_size_) -
    reinterpret_cast<char*>(&status_) + sizeof(args_size_));
}

bool RpcResponseHeader::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RpcResponseHeader)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .ErrorCode status = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_status(static_cast< ::ErrorCode >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "RpcResponseHeader.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 args_size = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &args_size_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RpcResponseHeader)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RpcResponseHeader)
  return false;
#undef DO_
}

void RpcResponseHeader::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RpcResponseHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ErrorCode status = 1;
  if (this->status() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->status(), output);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "RpcResponseHeader.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  // int32 args_size = 3;
  if (this->args_size() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->args_size(), output);
  }

  // @@protoc_insertion_point(serialize_end:RpcResponseHeader)
}

::google::protobuf::uint8* RpcResponseHeader::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:RpcResponseHeader)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ErrorCode status = 1;
  if (this->status() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->status(), target);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "RpcResponseHeader.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  // int32 args_size = 3;
  if (this->args_size() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->args_size(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:RpcResponseHeader)
  return target;
}

size_t RpcResponseHeader::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RpcResponseHeader)
  size_t total_size = 0;

  // string message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // .ErrorCode status = 1;
  if (this->status() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->status());
  }

  // int32 args_size = 3;
  if (this->args_size() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->args_size());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void RpcResponseHeader::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RpcResponseHeader)
  GOOGLE_DCHECK_NE(&from, this);
  const RpcResponseHeader* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RpcResponseHeader>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RpcResponseHeader)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RpcResponseHeader)
    MergeFrom(*source);
  }
}

void RpcResponseHeader::MergeFrom(const RpcResponseHeader& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RpcResponseHeader)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.status() != 0) {
    set_status(from.status());
  }
  if (from.args_size() != 0) {
    set_args_size(from.args_size());
  }
}

void RpcResponseHeader::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RpcResponseHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RpcResponseHeader::CopyFrom(const RpcResponseHeader& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RpcResponseHeader)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RpcResponseHeader::IsInitialized() const {
  return true;
}

void RpcResponseHeader::Swap(RpcResponseHeader* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RpcResponseHeader::InternalSwap(RpcResponseHeader* other) {
  message_.Swap(&other->message_);
  std::swap(status_, other->status_);
  std::swap(args_size_, other->args_size_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata RpcResponseHeader::GetMetadata() const {
  protobuf_rpc_5fresponse_5fheader_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_rpc_5fresponse_5fheader_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// RpcResponseHeader

// .ErrorCode status = 1;
void RpcResponseHeader::clear_status() {
  status_ = 0;
}
::ErrorCode RpcResponseHeader::status() const {
  // @@protoc_insertion_point(field_get:RpcResponseHeader.status)
  return static_cast< ::ErrorCode >(status_);
}
void RpcResponseHeader::set_status(::ErrorCode value) {
  
  status_ = value;
  // @@protoc_insertion_point(field_set:RpcResponseHeader.status)
}

// string message = 2;
void RpcResponseHeader::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& RpcResponseHeader::message() const {
  // @@protoc_insertion_point(field_get:RpcResponseHeader.message)
  return message_.GetNoArena();
}
void RpcResponseHeader::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RpcResponseHeader.message)
}
#if LANG_CXX11
void RpcResponseHeader::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RpcResponseHeader.message)
}
#endif
void RpcResponseHeader::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RpcResponseHeader.message)
}
void RpcResponseHeader::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RpcResponseHeader.message)
}
::std::string* RpcResponseHeader::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:RpcResponseHeader.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* RpcResponseHeader::release_message() {
  // @@protoc_insertion_point(field_release:RpcResponseHeader.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void RpcResponseHeader::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:RpcResponseHeader.message)
}

// int32 args_size = 3;
void RpcResponseHeader::clear_args_size() {
  args_size_ = 0;
}
::google::protobuf::int32 RpcResponseHeader::args_size() const {
  // @@protoc_insertion_point(field_get:RpcResponseHeader.args_size)
  return args_size_;
}
void RpcResponseHeader::set_args_size(::google::protobuf::int32 value) {
  
  args_size_ = value;
  // @@protoc_insertion_point(field_set:RpcResponseHeader.args_size)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
